version: '3.8'
services:
  app:
    image: abderraoufmah/my-modified-image:latest
    volumes:
      - ./:/app
    stdin_open: true # Keeps STDIN open (-i)
    tty: true # Allocates a pseudo-TTY (-t)
    command: /bin/zsh # ⭐ Runs ZSH on startup
    ports:
      - "8000:8000" # Maps port 8080 on the host to port 8080 in the container
